### ISSUE TITLE
The future of GitFlow is unsure

### ISSUE THREAD

**Issue by brinkie2004** [jakobehn/GitFlow.VS#100]
Is this very handy plug-in going to be moved over to the new Git experience (and VS2022)?

**Comment by jakobehn** [comment]
Hi, sorry for not coming back on this sooner. I would very much like to, however I'm having trouble finding the correct integration point in the new Git changes window in VS2022. Need to dig into this more

**Comment by brinkie2004** [comment]
I just mentioned this plug-in and your issue porting it to VS2022 in the chat on a live YouTube video of Mads Kristenson here: https://youtu.be/2c-4uZc0rq0

He mentioned he'd be happy to help out, so maybe you can reach out to him?

**Comment by madskristensen** [comment]
Perhaps @Taysser-Gherfal knows something about the Git Changes window and its extensibility points

**Comment by dnviti** [comment]
Any update about 2022 support?

**Comment by jakobehn** [comment]
Not yet, haven't had time to investigate more on how to plug it into the new Git changes window in VS2022 (and later versions of VS2019).

Did @Taysser-Gherfal have any hints here?

**Comment by brinkie2004** [comment]
I can share firsthand that GitFlow still works fine in the current version of VS2019. It feels a bit detached, because it still uses the Team Explorer, but it is fully functional.

**Comment by jakobehn** [comment]
@brinkie2004 Yes that's true, porting it as is to VS2022 should be easy. I'll fix that, and then I need to revisit the issue of moving it into the new Git changes window

**Comment by jakobehn** [comment]
Turns out it wasn't that easy after all, for some reason the extension doesn't show up at all in Team Explorer. The extension loads correctly at startup (verified by debugging it) but it doesn't show up in Team Explorer. I'll keep digging into it

**Comment by brinkie2004** [comment]
Seems @fabiodella known a thing or two on how to integrate. Have you seen his hint here?
https://github.com/jakobehn/GitFlow.VS/issues/102#issuecomment-974218954

**Comment by fabiodella** [comment]
@brinkie2004 I don't know if it actually works, mine was a guess ... Watching this video[ [:](url)](https://www.youtube.com/watch?v=mCxdeRrZ7LE&list=PLReL099Y5nRdz9jvxuy_LgHFKowkx8tS4&index=4)  , I found this tag, I don't know if this source code is reversible / useful to the cause

**Comment by jakobehn** [comment]
I finally got some time to dig into this and just published a new extension that supports Visual Studio 2022. Please spread the word :-)

https://marketplace.visualstudio.com/items?itemName=vs-publisher-57624.GitFlowforVisualStudio2022

**Comment by raymondbrink** [comment]
Awesome! I'll give it a spin and will let you know my findings here ASAP!

Update: No issues found sofar. Amazing to have this plugin again in VS2022!
Thanks @jakobehn

**Comment by jorgelevy** [comment]
> I finally got some time to dig into this and just published a new extension that supports Visual Studio 2022. Please spread the word :-)
> 
> https://marketplace.visualstudio.com/items?itemName=vs-publisher-57624.GitFlowforVisualStudio2022

Amazing!! Thanks for your hard work!!!
