### ISSUE TITLE
GitFlow for VS2022

### ISSUE THREAD

**Issue by fabiodella** [jakobehn/GitFlow.VS#102]
Hello, is there a new version for Visual Studio 2021 planned?

**Comment by jakobehn** [comment]
I guess you mean Visual Studio 2022. I'm working on it, I'm having some problem with getting the extension to show up in the Team Explorer unfortunately

**Comment by j-dc** [comment]
> I guess you mean Visual Studio 2022. I'm working on it, I'm having some problem with getting the extension to show up in the Team Explorer unfortunately

Is there a reason you want it in team explorer?   Git has moved completely away from the team-explorer window? 
![image](https://user-images.githubusercontent.com/8330653/142636752-ede9feb1-2556-4ac0-bbb8-92fe12141d2f.png)

Wouldn't it be more 'maintainable' to create a 'gitflow' window that does just that?  Or if you want it to embed somwhere, it should be in 'manage branches ' imho?

**Comment by fabiodella** [comment]
Yes, sorry I meant VS2022 ... Have you tried using the tag  `LogCanonicalName `.TeamExplorer.Project  `/LogCanonicalName`  in the manifest ?

**Comment by aarondglover** [comment]
@jakobehn . I love this extension. Can't wait to use it in VS2022.

**Comment by jakobehn** [comment]
New extension that supports Visual Studio 2022 has just been published:
https://marketplace.visualstudio.com/items?itemName=vs-publisher-57624.GitFlowforVisualStudio2022
