### ISSUE TITLE
Finishing a feature takes a long time without much indication of progress

### ISSUE THREAD

**Issue by pcolmer** [jakobehn/GitFlow.VS#12]
I've just used the Finish feature function for the first time and the progress bar is just moving and moving and moving.
The output from GitFlow.VS is rather sparse. I'd like some confirmation that it is actually doing something and not stuck somewhere ...

**Comment by pcolmer** [comment]
I'd also like some reassurance/information as to what the heck happens if I click on Cancel while the progress bar is going on ...

**Comment by jakobehn** [comment]
Thanks. I redirect all output from GitFlow to a separate Output window.  What happens if you run the same command from command line? (git flow feature finish X) 

There was another similar issue that was due to gitflow prompting for credentials, that the extension doesn't (currently) handle.

And regarding the Cancel button, it should be disabled when running the command, thats a bug

**Comment by pcolmer** [comment]
At the moment, the finish feature is still running. VS is on the Output tab and is set to show output from GitFlow.VS but all it is saying is:

Running git flow feature finish "PreviousVersionMigration"

and it has been saying that for quite some time now ... well, at least for as long as I created this issue :-).

If the Cancel button should be disabled, does that mean I can't disable the current activity? What should I do? Quit VS and hope it closes stuff down properly?

I'm reluctant to try the command line until/unless I know that VS isn't going to get in the way.

Thanks.

**Comment by pcolmer** [comment]
OK - I finally gave on VS and quit it and restarted it.
Tried "git flow feature finish" from the command line and it prompts for a username, so I guess I'm hitting the same issue.

**Comment by jakobehn** [comment]
See comment on https://github.com/jakobehn/GitFlow.VS/issues/9. I just published a new version that works around this by adding a timeout and a notification message. It doesn't solve the problem, but it stops the extension from hanging
