### ISSUE TITLE
can't see features created in another computer

### ISSUE THREAD

**Issue by lucamorelli** [jakobehn/GitFlow.VS#13]
Hi, I just created a new feature using vs 2015 ctp 6, done some changes and published all to git. At this point I have reopen it in my laptop using vs 2013: After the git sync, I initialized without problems gitflow for this project in the laptop, but I can't see the feature I created. If I try to create a new features I receive the error message that the branch is already present, but I don't see it in the feature list.
How can I solve this?

**Comment by jakobehn** [comment]
Hi, in order to "see" remote branches you need to track them (e.g. create a local branch that tracks the remote branch). 

I haven't implemented this yet in the extension, in the mean time you should be about to do this from command line:

git flow feature track <featureName>

**Comment by lucamorelli** [comment]
thank you very much, worked fine
