### ISSUE TITLE
Finishing hotfix results in conflicts

### ISSUE THREAD

**Issue by pcolmer** [jakobehn/GitFlow.VS#14]
One of the outputs from starting a hotfix is to bump the version number. I did this, checked in the changes and then finished the hotfix but I ended up with conflicts:

Running git flow hotfix start "HotFix-IntParseFailure"
Summary of actions:
- A new branch 'hotfix/HotFix-IntParseFailure' was created, based on 'master'
- You are now on branch 'hotfix/HotFix-IntParseFailure'

Follow-up actions:
- Bump the version number now!
- Start committing your hot fixes
- When done, run:

     git flow hotfix finish 'HotFix-IntParseFailure'

Running git flow hotfix finish -n "HotFix-IntParseFailure"Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
Merge made by the 'recursive' strategy.
 RelHist2/RelHist2.Shared/Model/RHDate.cs               |  2 ++
 RelHist2/RelHist2.Shared/Model/RHFile.cs               | 18 +++++++++++++-----
 .../ViewModel/SourceCitationViewModel.cs               |  8 ++++----
 RelHist2/RelHist2.Windows/Package.appxmanifest         |  2 +-
 RelHist2/RelHist2.WindowsPhone/Package.appxmanifest    |  2 +-
 5 files changed, 21 insertions(+), 11 deletions(-)
Fatal: There were merge conflicts.
Auto-merging RelHist2/RelHist2.WindowsPhone/Package.appxmanifest
CONFLICT (content): Merge conflict in RelHist2/RelHist2.WindowsPhone/Package.appxmanifest
Automatic merge failed; fix conflicts and then commit the result.

I resolved the conflicts and finished the merge but GitFlow.VS doesn't think I'm in the middle of doing anything, so I still have the hotfix branch and I'm not sure what I should be doing to clean it up. I *think* can remove the hotfix branch as it looks like the develop branch has been updated, but I'm not sure.
I'm also not sure how I managed to get my branches into a state where there were merge conflicts. The ONLY conflict was in the version number.

**Comment by jakobehn** [comment]
I can't really say anything about the merge conflict without looking at the repo.  With regards to the state after performing a manual merge, you should be able to run Finish Hotfix again. Since there is nothing to merge, nothing will happen with respect to that, and the HF branch will be removed. Did you try this?

**Comment by pcolmer** [comment]
I have successfully finished the hotfix via the command line. It wasn't possible to do it via the GUI as the GUI didn't think I was still working on a hotfix.

**Comment by jakobehn** [comment]
Did you try it, from the Other Actions menu? I'm guessing that when you ran Finish the first time it did switch your current branch to develop, which would cause the extension to not suggest Finish hotfix as the recommended action. But you can always find all actions in the Other Actions menu

**Comment by pcolmer** [comment]
I thought I had looked on the Other Actions menu but I clearly hadn't!

Thanks.
