### ISSUE TITLE
InstrumentationKey cannot be empty.

### ISSUE THREAD

**Issue by kkbruce** [jakobehn/GitFlow.VS#16]
Hi

I sing Visual Studio 2013 to create default mvc project, then add to Git source control.

Click GitFlow always display 'InstrumentationKey cannot be empty.' error message.

http://i.imgur.com/fqbknD8.png

Bruce

**Comment by jakobehn** [comment]
Seems to be an issue with the instrumentation. Can you look in the installation folder of the extension (located at %localappdata%\Microsoft\VisualStudio\12.0\Extensions\<GUID>). The guid is different so you need to browse throught the different folders.   In the folder for GitFlow.VS, there should be a ApplicationInsights.config file. Can you verfify if that file is there or not?

Also: Which version of the extension are you using?

**Comment by kkbruce** [comment]
http://i.imgur.com/A0RCwRG.png
ApplicationInsights.config is here, and content:

&lt;?xml version="1.0" encoding="utf-8"?>
&lt;ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings" schemaVersion="2014-05-30">
	&lt;TelemetryChannel>
		&lt;DeveloperMode>false&lt;/DeveloperMode>
	&lt;/TelemetryChannel>
  &lt;TelemetryModules>
    &lt;Add Type="Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule, Microsoft.ApplicationInsights"/>
  &lt;/TelemetryModules>
	&lt;InstrumentationKey>0aafb28d-ec58-4d70-b42c-ad53134bee79&lt;/InstrumentationKey>
	
&lt;/ApplicationInsights>

GitFlow version is 0.9.22.

Thanks

**Comment by jakobehn** [comment]
That look correct. Have you tried uninstall/reinstall? I will add better error handling to the instrumentation code so that it doesn't block the extension from running properly if it fails

**Comment by jakobehn** [comment]
This issue should be fixed in the latest version. I don't read the information from the configuration file anymore (this is deprecated)
