### ISSUE TITLE
The command is taking longer than expected

### ISSUE THREAD

**Issue by galvesribeiro** [jakobehn/GitFlow.VS#17]
Installing the GitFlow on VS2015, each operation that involve changing the remote repository, like publish a feature branch or finish it, receives a "The command is taking longer than expected" on either team explorer or output window and we have to do it manually on git console. Note that we are using VSO for our repositories for the sake of information.

WHat is wrong?

Thanks

**Comment by denissezavala** [comment]
I'm also having this issue in VS2013, any updates?

**Comment by jakobehn** [comment]
This is most likely because of git is prompting for credentials. See issue #9 for a discussion.

If so, the solution is to add the credentials to the credential store (this is a good idea even if you don't use this extension!). See more info on issue #9
