### ISSUE TITLE
support for "-" in prefixes

### ISSUE THREAD

**Issue by titov-ps** [jakobehn/GitFlow.VS#18]
We use prefixes like feature- or hotfix- 
When I start feature "XXX" it displays it as "feature-XXX", and when you try to finish the feature it tries to merge branch "feature-feature-XXX" which doesn't exist.

I think the bug is in function GetAllBranchesThatStartsWithConfigPrefix
the code c => c.Name.Split('/').Last() is wrong
It should not depend on "/" character, it should just remove prefix

**Comment by jakobehn** [comment]
Thanks for the report, I'll get that fixed
