### ISSUE TITLE
Feature request. ...Feature pull

### ISSUE THREAD

**Issue by ingodan** [jakobehn/GitFlow.VS#25]
Would be nice to be able to pull a remote feature in (e.g. git flow feature pull origin MYFEATURE)

**Comment by jakobehn** [comment]
Thanks, I actually started with this right before releasing the first version, but never got around to finish it. I'll look into it soon, need to decide on how to display local and remote feature branches in the list view

**Comment by ingodan** [comment]
That is awesome :+1:

**Comment by jakobehn** [comment]
I just committed this feature, but I decided to go with Track instead of Pull. I don't really see the point of doing a Pull in git flow, since it apparently only creates a local branch but doesn't track the remote branch?  What are the use cases for running git flow pull?
