### ISSUE TITLE
Visual studio 2015 Always crashes when finishing a hotfix,feature,release

### ISSUE THREAD

**Issue by ingodan** [jakobehn/GitFlow.VS#26]
I have VS 2015. The features/Hotfixes/Release branches do get merged correctly but for some reason Visual studio always crashes. This happens for everyone in my 5 man team ;)

**Comment by jakobehn** [comment]
Thanks for the report. Would it be possible for yoú to start Visual Studio with the /log flag turned on (devenv.exe /log) and then upload the ActivityLog.xml file, to see if i can understand more about the issue?

Thanks

**Comment by TechInceptions** [comment]
I believe this is related to merge markers in the project file (.csproj or .vbproj)

The project files are xml based and Git merge-markers use angle brackets.

Angle brackets breaks the Xml, and VS crashes when it tries to load the "corrupt" xml file.

**Comment by yannduran** [comment]
I've also had this happen quite a lot (though not every single time, just often), although not recently I've just realised as I was writing this.

**Comment by jakobehn** [comment]
Although not a fix of the root cause(s), I have added error handling now so that these kind of problems won't bring VS down, and it also shows the error information in the Team Explorer windows.
