### ISSUE TITLE
vs 2015 build

### ISSUE THREAD

**Issue by scrubs767** [jakobehn/GitFlow.VS#27]
I have tried to build this and I cant seem to get it to build, it is missing references to microsoft.visualstudio.setting and TeamExplorer.Common.dll. I can't seem to find the right combination of nuget packages to get it to build. Do you have some insight on this?

**Comment by jakobehn** [comment]
You need to have the VS2015 SDK installed to be able to compile it. As soon as the NuGet packages for the Team Explorer extensibility model is available I will switch to them

**Comment by scrubs767** [comment]
I do have it installed, maybe something happened during installation. I''l try reinstalling, thank you

**Comment by jakobehn** [comment]
There are different configurations, one for VS2013 and one for VS2015. If you only have VS2015SDK installed, make sure you select the VS2015 configuraiton

**Comment by scrubs767** [comment]
I tried that, still the same error. I installed vs 2013 and the vs 2013 sdk (you cant install vs 2013 sdk with having vs 2013 installed) and it complied fine. So it appears you have to have both sdks installed to get it to compile.

**Comment by jakobehn** [comment]
I just checked in a fix for this, it was one of the references that wasn't correctly setup. You can now build and run the project with only VS2015 + SDK installed.

Thanks for reporting!
