### ISSUE TITLE
GitFlow 0.10.12.0 fails to install properly

### ISSUE THREAD

**Issue by TechInceptions** [jakobehn/GitFlow.VS#28]
Installed GitFlow on a client's Corporate computer (VS 2015.1), but "Initialize" fails with the following error message

**Running git flow init -f fatal: 'flow' appears to be a git command, but we were not**

It seems related to missing files or environment variables.

I repeated the install, this time openning VS 2015.1 with "Run as Administrator", but with the same results.

I suspect that it's related to security or policy on this one computer.

Which folders or settings could I check to confirm the installation?

Thanks

**Comment by jakobehn** [comment]
It seems like git flow wasn't installed properly. When installing the GitFlow.VS extensions it automatically runs and configure git-flow, so you should be able to open a git command prompt and run git flow.

Have you tried reinstalling the extension?

**Comment by jakobehn** [comment]
Closing this one since no response
