### ISSUE TITLE
GitFlow Doesn't Always Appear in Home Dropdown List

### ISSUE THREAD

**Issue by yannduran** [jakobehn/GitFlow.VS#29]
When you click on the Home icon, you can see the GitFlow icon. When you click the dropdown next to the selected function in the Home tab GitFlow doesn't appear in the list.

To reproduce this:

1. Click on the GitFlow icon in the Home tab (GitFlow DOES appear at the top of the dropdown list, and is ticked)
2. Select Changes (or any other item in the dropdown list), make a commit (though not necessary to do this to see the problem)
3. Try to go back to GitFlow using the dropdown again (GitFlow is NOT in the list, like Changes, Branches etc is)

I love using GitFlow, and I also use the Team Explorer dropdown a lot to switch between Team Explorer functions (eg clicking Changes, making a commit, then clicking Sync, then maybe clicking Work Items). Not having GitFlow in the dropdown means that I always have to go back to the Home tab first (using the Home icon), then click on the GitFlow icon. I can use the dropdown for everything except GitFlow.

**Comment by jakobehn** [comment]
Thanks, that is correct. I haven't actually added it to the drop down menu. I thought that would be done automatically, but apparently I need to to this explicitly. I'll fix this in the next release

**Comment by yannduran** [comment]
Thanks Jakob. If I knew how to do it myself, I'd have forked your repository and sent a pull request with the updated code. Do you have a rough idea when the "next release" might be released? Thanks!

**Comment by jakobehn** [comment]
Thanls Yann, I\ve started work on the next release so it shouldn't be that long (I know, famous last words.. )

**Comment by yannduran** [comment]
:-)

**Comment by jakobehn** [comment]
It was a quick fix, so I just commited this change. Will be part of the next release

**Comment by yannduran** [comment]
Thanks Jakob, I'll download it and check it out

**Comment by scrubs767** [comment]
Hello, I wrote an extension that has this same problem, I tried quickly looking through the commits you had at the time but nothing stuck out, can you point me in the right direction?
