### ISSUE TITLE
vs 2015  Installation errors

### ISSUE THREAD

**Issue by cuibty** [jakobehn/GitFlow.VS#30]
I have installed git version 2.6.3.windows.1 and use this method to install a https://github.com/nvie/gitflow/wiki/Windows#git-for-windows-previously-msysgit gitflow, in vs 2015 update 1 is installed Gitflow for Visual Studio 2015.
![1](https://cloud.githubusercontent.com/assets/12811343/12013535/81d0fa7a-ad53-11e5-8441-857df0cc6b37.jpg)

**Comment by Fearodin** [comment]
Had the same issue with the latest git-version and vs2015. Try to re-install git and restart vs2015. That worked for me.

**Comment by jakobehn** [comment]
I'm considering adding an option here to let the user manually specify the path if the addin can't locate it automatically. I'm currently evaluating 3 or 4 different ways of getting the installation path (check file paths, registry setttings..)  

Thoughts?

**Comment by Fearodin** [comment]
Hey, thankts for your reply. I think this would be very helpful, thanks
dude :)
Cheers

2016-01-15 13:45 GMT+01:00 Jakob Ehn <notifications@github.com>:

**Comment by jakobehn** [comment]
I have just uploaded a new version (1.0.3.0) that should solve this problem
