### ISSUE TITLE
"Could not read password..." when finishing hotfix/feature

### ISSUE THREAD

**Issue by raphzack** [jakobehn/GitFlow.VS#31]
When I want to finish a hotfix I always get the message "fatal: could not read Password for 'https://...'

When I do the steps (merge to master and develop, push everything, delete the hotfix-branch...) manually it works.

When I call 'git flow hotfix finish hotfixname' in cmd everything works fine.

Any ideas?

Additional info:
I am using bitbucket for remote repos

**Comment by raphzack** [comment]
I did some further tests and added the password into the https-url in my git config file
It now looks like this:

[remote "origin"]
url = https://<user>:<password>@bitbucket.org/path/to/user/repos.git

Finish features and/or hotfixes is now possible but this is not my prefered solution.

**Comment by jakobehn** [comment]
Thanks for the report. So, you are saying that if you copy the exact same command that the VS addin is outputting in the Output Window and run it from command line, it works? Is there anything different in how you authenticate against the repo? I haven't seen/heard about this problem before.

**Comment by raphzack** [comment]
Yes I run the following command from command line: git flow hotfix finish hotfixname

During the "finish" I had to enter my password twice and a vim-editor opens for entering a comment for the tag.

**Comment by raphzack** [comment]
I am not sure why VS never asks me for my password but obivously all the other push/fetch/fill commands are working fine so the password seems to be stored somewhere.

Is it possible to run the commands with a debug flag or sth. to get more information what happens in the background?

**Comment by jakobehn** [comment]
There have been other issues that are caused by the fact that git prompts for credentials (in a way that is very hard for the extension to handle unfortunately). Have you tried using the git credential manager for Windows? Seehttps://github.com/jakobehn/GitFlow.VS/issues/9 for more details. 

It will prompt you for your credential the first time you push something and then store it in the Windows credential store.

There was recently a brand new version of this tool, it is available here: https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.0.0

**Comment by raphzack** [comment]
I installed the credential manager now but still have the same problem.
I then removed all the entries for bitbucket in my windows credential manager. When I sync/push/pull my repo now I have to enter my credentials in a popup (as expected). For some reason this popup doesn't appear, when I want to finish my release/hotfix.

**Comment by jakobehn** [comment]
I reproduced this now, I created a repo on BitBucket and then I cloned it and initialized it using the GitFlow extension. Finishing (and pushing>) a hotfix worked just fine. Then I went into the Credential Manager and removed the cached BitBucked credential. Then, when trying to finish a hotfix (with push) using the extension I get the same error:

Merge made by the 'recursive' strategy.
 WebApplication1/WebApplication1/Controllers/AccountController.cs | 2 ++
 1 file changed, 2 insertions(+)
Deleted branch hotfix/hf8 (was c2482cf).
**fatal: could not read Password for 'https://jakobehn@bitbucket.org/': No error
Fatal: Could not push branch 'develop' to remote 'origin'.**

The question is why you get the error even though you have the credential stored in CM?

**Comment by raphzack** [comment]
I cached my credentials now in the CM again and finishing using the extension was successfully. I don't know what is different than in the morning apart from the fact that I removed all entries and stored them again now (probably the git-credential-manager does something?)

But why doesn't a popup prompt when I remove the credentials from CM and try to finish a feature using the extension?

Another question (sorry I just remember it now as I started from the scratch the way you discribed / or better open a new issue?): When I cloned my bitbucket repo and initialized it using the extension  and use all the defaults from the 'initialize-view', I am not able to start a hotfix or feature. I get the error: Fatal: Version tag not set. Please run 'git flow init'. 

The config file after initializing has only:
[gitflow "prefix"]
    feature = feature/

Where are all the other prefixes? After I add the versiontag manually to the config and start a hotfix again, I get the message, that the Hotfix prefix is not set. It looks like that not all settings are written to the StandardInput correctly. 


Sorry, I didn't want that message get that long. I think I should open another issue? But probably both problems have the same basic cause.

Just one question as I am not familiar with writing VS extensions and I am also new to git (unbelievable but my company is still using svn). Which steps do I have to go, when I want do debug the extension and modify the code after cloning this repo and creating a branch?

BTW: I am using 
- Win 10 Prof
- VS 2015
- latest Git for Windows

**Comment by jakobehn** [comment]
I've seen another report of the "version tag not set" error, so I need to look into that. Could you perhaps open a separte issue for this? Thanks!

I have added a separate issue for documentation around prerequirements for compiling and debugging the extension. Expect to see it soon.

**Comment by raphzack** [comment]
I opened a new issue.
As I do not have any problems with that issue at the moment (as long as my credentials are stored in the CM), I will close it now.

Thank you!
