### ISSUE TITLE
Problems building the source VS2015 Community

### ISSUE THREAD

**Issue by McDoit** [jakobehn/GitFlow.VS#32]
I downloaded the source and did some checking around, but when i try to build the GitFlow.VS.Extension project i get the following error:

    The "ReadReferencesFromVsixManifest" task was not given a value for the required parameter "InputFile".	GitFlow.VS.Extension

I had to do some nuget restore and other stuff to get it to build the other projects, resolving them etc, but is this something anyone has encountered before?

**Comment by jakobehn** [comment]
You must have the Visual Studio 2015 SDK installed in order to compile the project.

**Comment by McDoit** [comment]
Just double checked and it is apparently there (Visual Studio 2015 Extensibility Tools).
Coming to think about it i might accidently have switched the refs to the ones that are nuget based when fiddeling around

**Comment by jakobehn** [comment]
Could you check with the latest version of the codebase? Earlier today I checked in a fix where the VS2015 configuration wouldn't build if VS2013 was missing.  Also, make sure that you build the VS2015 configuration

**Comment by McDoit** [comment]
I pulled the new into my fork, rebased and checked out your latest commit, still the same error

![image](https://cloud.githubusercontent.com/assets/16723686/12434469/1780e7aa-bf07-11e5-8528-1827076e50d4.png)

And cant really find any relevant information about the error, it seems to be "ungoogleable"!

When i try to edit the vsixmanifest file it all looks good except this part:

![image](https://cloud.githubusercontent.com/assets/16723686/12434437/e0e59ace-bf06-11e5-97dd-a8dd82752528.png)

**Comment by McDoit** [comment]
Finally solved it with here
Guess it failed when i didnt chose the right config to build from

and then i followed this to setup debuging:
http://stackoverflow.com/questions/9281662/how-to-debug-visual-studio-extensions

Thanks Jakob!

**Comment by jakobehn** [comment]
Thanks for getting back! This is information that I should have in the readme for this repo, I'll add an issue to get this done

**Comment by Deren-Liao** [comment]
Hi McDoit,
How did you solve the problem actually?  I am facing the same problem.

**Comment by hanoversurf** [comment]
Hi Deren-Liao,
I had the same problem. I solved it by changing the Solution Configuration from Debug to VS2015.
Best Regards
Marco
