### ISSUE TITLE
GitFlow release push to remote fails

### ISSUE THREAD

**Issue by heatmonkey** [jakobehn/GitFlow.VS#39]
Running git flow release start "Arcus-0.1.1"

Summary of actions:
- A new branch 'release/***-0.1.1' was created, based on 'develop'
- You are now on branch 'release/***-0.1.1'

Follow-up actions:
- Bump the version number now!
- Start committing last-minute fixes in preparing your release
- When done, run:

     git flow release finish '***-0.1.1'

Running git flow release finish "***-0.1.1" -n -k -p
fatal: could not read Username for '[[my tfs server name]]': Invalid argument
Fatal: Could not push branch 'develop' to remote 'origin'.

**Comment by jakobehn** [comment]
Hi, is this using the GitFlow Visual Studio extension or are you doing this from the command line?

**Comment by heatmonkey** [comment]
This is from within visual studio

**Comment by yannduran** [comment]
I also have problems pushing a release (by ticking checking the "push" box) during "Finish Release". For me I eventually get an error message indicating that it has timed out.

If I don't check the box during "Finish Release", and then push manually it works fine.

**Comment by eloekset** [comment]
I've also got this error message about username. I get it when trying to finish a feature. First the GitFlow TeamExplorer displays this error message: Fatal: Could not fetch feature from origin.
![2016-03-02_1608](https://cloud.githubusercontent.com/assets/791721/13464347/131021bc-e091-11e5-8db6-b3ebb2cb8664.png)

My complete GitFlow.VS log is:
```
Running git flow init -f
Fatal: Working tree contains unstaged changes. Aborting.
Running git flow init -f

Which branch should be used for bringing forth production releases?
   - master
   - typeScript
Branch name for production releases: [master]
 
Which branch should be used for integration of the "next release"?
   - typeScript
Branch name for "next release" development: []
Fatal: Local branch 'develop' does not exist.
Running git flow init -f

Which branch should be used for bringing forth production releases?
   - master
Branch name for production releases: [master]
 Branch name for "next release" development: [develop]
 
How to name your supporting branch prefixes?
Feature branches? [feature/]
 Bugfix branches? [bugfix/]
 Release branches? [release/]
 Hotfix branches? [hotfix/]
 Support branches? [support/]
 Version tag prefix? []
 Hooks and filters directory? [C:/account-name.vsonline.com/Playground/ExportManagement/.git/hooks]
Running git flow feature start "typeScriptModularity"

Summary of actions:
- A new branch 'feature/typeScriptModularity' was created, based on 'develop'
- You are now on branch 'feature/typeScriptModularity'

Now, start committing on your feature. When done, use:

     git flow feature finish typeScriptModularity

Running git flow feature finish "typeScriptModularity" -r
Fatal: Working tree contains unstaged changes. Aborting.
Running git flow feature finish "typeScriptModularity" -r
fatal: could not read Username for 'https://account-name.visualstudio.com': Invalid argument
Fatal: Could not fetch feature/typeScriptModularity from origin.
Running git flow feature finish "typeScriptModularity" -r -k
fatal: could not read Username for 'https://account-name.visualstudio.com': Invalid argument
Fatal: Could not fetch feature/typeScriptModularity from origin.
Running git flow feature finish "typeScriptModularity" -r -k
fatal: could not read Username for 'https://account-name.visualstudio.com': Invalid argument
Fatal: Could not fetch feature/typeScriptModularity from origin.

```

**Comment by jakobehn** [comment]
This looks related to authentication problem. Have you tried using the git credential manager to store your credentials for the remote repo (VSTS in your case)? This will cache your credentials in the Windows Credential Manager.

https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.2.0

Let me know if this helps

**Comment by eloekset** [comment]
@jakobehn The Credential Manager fixed the issue in my case. I did a simple feature just to test. This is the log, showing that it works as expected without any error message:
```
Running git flow feature finish "newTestFeature"
Your branch is ahead of 'origin/develop' by 1 commit.
  (use "git push" to publish your local commits)
Updating 17fcd67..37a98bf
Fast-forward
ExportManagement.Web/App_Start/BundleConfig.cs | 1 +
 1 file changed, 1 insertion(+)
Deleted branch feature/newTestFeature (was 37a98bf).

Summary of actions:
- The feature branch 'feature/newTestFeature' was merged into 'develop'
- Feature branch 'feature/newTestFeature' has been locally deleted; it has been remotely deleted from 'origin'
- You are now on branch 'develop'
```

Maybe this will fix the issue for @heatmonkey as well?

**Comment by MrDark** [comment]
I just had the same problem and installing the credential manager fixed it.

**Comment by jakobehn** [comment]
Closing this issue now
