### ISSUE TITLE
Finish Release action creates an extra back merge into develop

### ISSUE THREAD

**Issue by maulik13** [jakobehn/GitFlow.VS#42]
When I do a finish release action, I always end up getting a "back merge" into the develop branch. This adds an unnecessary merge commit to my develop branch. I see that there is an option in GitFlow package that allows you to control this option. Any plan to add this to the VS extension?

**Comment by jakobehn** [comment]
Is that the -b option, that you are referring to?

b,[no]nobackmerge   Don't back-merge master, or tag if applicable, in develop

https://github.com/petervanderdoes/gitflow-avh/blob/develop/git-flow-release#L600

**Comment by maulik13** [comment]
@jakobehn yes that is correct. It is -b option in the link you mentioned :)

**Comment by jakobehn** [comment]
I'll add this to the next release

**Comment by maulik13** [comment]
That would be great! Thanks :)
