### ISSUE TITLE
Finish feature and TFS Pull Requests

### ISSUE THREAD

**Issue by jdpilgrim** [jakobehn/GitFlow.VS#43]
When you finish a feature you can choose to delete the feature branch. It deletes the branch locally and remotely. That fine and all, however, it does not play so well with TFS Pull Requests. If the code only deleted the local branch, you could then go to tfs and it will allow you to complete the Pull Request. With the current behaviour the Pull Request is marked as abandoned.

You can control this deletion using these flags.
[https://github.com/jakobehn/GitFlow.VS/search?utf8=%E2%9C%93&q=keepremote](https://github.com/jakobehn/GitFlow.VS/search?utf8=%E2%9C%93&q=keepremote)

```

k,[no]keep             Keep branch after performing finish
keepremote!        	   Keep the remote branch
keeplocal!             Keep the local branch
```

**Comment by jakobehn** [comment]
Thanks, so just to be clear: You are suggesting the the extension expose these options in the finish feature UI?

**Comment by jdpilgrim** [comment]
That would definitely be acceptable. I've tried implementing just that in pull request #44.

**Comment by jakobehn** [comment]
Thanks a lot for PR. I've merged it (just adding a test for it) and will release it in the 1.1 release

**Comment by jdpilgrim** [comment]
No worries. Thanks adding a test :)

**Comment by cosmoKenney** [comment]
I know this is closed, but is there any way to set these as defaults? I.e. delete local, leave remote alone?
