### ISSUE TITLE
Visual Studio Tools for Apache and now extension not finding Gitflow

### ISSUE THREAD

**Issue by trendoid** [jakobehn/GitFlow.VS#45]
I have Gitflow installed.  It works fine via command line.  But with the latest Visual Studio Tools for Apache Cordova the GitFlow Extension doesn't work anymore.

**Comment by jakobehn** [comment]
Thanks for the report. Do you have any more information, any errors in the UI or in the outut window?

**Comment by trendoid** [comment]
The powershell script that runs says that "GitFlow already installed" and closes.. it happens really fast.  I ran it manually and it does the same thing.

**Comment by jakobehn** [comment]
I have installed the latest version (Update 7) of the VS Cordova Tools  on two different machines, but I can't reproduce any error

**Comment by jakobehn** [comment]
Closing this one since I can't reproduce it
