### ISSUE TITLE
GitFlow can't find VS' git

### ISSUE THREAD

**Issue by realsonic** [jakobehn/GitFlow.VS#46]
I have no standalone git installed, but I'm using VS Community 2015 builtin git. And GitFlow can't find it.

**Comment by jakobehn** [comment]
GitFlow uses Git for Windows (https://git-scm.com/download/win), which is not installed with Visual Studio 2015. So you need to install this before using gitflow

**Comment by realsonic** [comment]
@jakobehn Can TF git support be added to GitFlow plugin as a featue in future?

**Comment by jakobehn** [comment]
The plugin searches for existing msysgit installations in multiple places, so it should find it it's installed.  
I have currently no plans to rewrite the implementation that uses the gitflow scripts from the AVH fork (https://github.com/petervanderdoes/gitflow-avh)

Thanks
