### ISSUE TITLE
New feature: wrong author and update time

### ISSUE THREAD

**Issue by realsonic** [jakobehn/GitFlow.VS#50]
I've just created a feature (gsc-62) and extension shows wrong author (not me) and wrong update time (3 hours instead of just now):
![image](https://cloud.githubusercontent.com/assets/2719939/14080647/23528d3e-f50f-11e5-9808-53f4abb1d190.png)

**Comment by jakobehn** [comment]
This is how Git works, when you create a branch you just create a pointer to the last commit, which in this case was done three hours ago by someone else. As soon as you commit something in your branch, you will see your name and timestamp there

**Comment by realsonic** [comment]
@jakobehn May be in this case the best choice is show something like "Just created" or other initial message?

**Comment by jakobehn** [comment]
Closing this one. All Git tools behaves this way (e.g. showing the info of the latest commit)
