### ISSUE TITLE
Starting a new feature with an apostrophe (') in the name fails

### ISSUE THREAD

**Issue by HarroSchmidt** [jakobehn/GitFlow.VS#55]
Starting a new feature with an apostrophe (') in the name fails.

When for example starting a feature with the name "Test's" the output windows shows: 
Running git flow feature start "Test's"

After that nothing happens.

Solution: The apostrophe should be removed before calling the git method.

**Comment by jakobehn** [comment]
Thanks, I'll fix this in the next releaes

**Comment by jakobehn** [comment]
This is fixed in the 2017 version
