### ISSUE TITLE
TFS 2015 Manage Extensions fails with invalid Publisher

### ISSUE THREAD

**Issue by cspandex** [jakobehn/GitFlow.VS#57]
Noticed when I tried to upload the vsix into a TFS 2015 instance it was rejected due to an invalid Publisher value. 

Error message. 

The Publisher name 'Jacob Ehn' is invalid. Publisher names may only contain 'A' through 'Z', 'a' through 'z', '0' through '9', '.' and '-'. The Publisher name must start with an alphabetic or numeric character.

**Comment by jakobehn** [comment]
This is a Visual Studio extension, it is not a TFS/VSTS extension.
