### ISSUE TITLE
Cannot install Gitflow: Could not locate Git for Windows on this machine. 

### ISSUE THREAD

**Issue by arame3333** [jakobehn/GitFlow.VS#58]
I am using Visual Studio 2015 and I have just installed Gitflow.
Or I thought I had. But when I look at Gitflow I see this message;

Could not locate Git for Windows on this machine. This is required for Gitflow. Please install and try again

I am using Git for my project, so I am not sure why this message is appearing.

**Comment by jakobehn** [comment]
The GitFlow scripts that this extension is using requires Git for Windows to be installed. You can install it from here https://git-scm.com/download/win

Visual Studio 2015 doesn't use Git for Windows, but instead uses the LigGit2Sharp which is a Git implementation for .NET (https://github.com/libgit2/libgit2sharp).

(In VS 2017, MS has actually rewritten the Git integration. They have dropped the use of LibGit2Sharp and instead ships with Git for windows)

**Comment by arame3333** [comment]
Hi Jakob,
I run the Git for Windows extension but I still have the same problem.
I did not install LigGit2Sharp as judging from your email I do not need it, although I do not know why you sent me the link. Did I misunderstand you?

Geoff (0777 5853 204)


Geoffrey Payne 
ICT Software Developer
Tel: 020 8551 9999
www.mulalley.co.uk
Consider the environment. Do you really need to print this email?
Registered Office: Teresa Gavin House, Woodford Avenue, Woodford Green, Essex IG8 8FA
Company No. 1534913
VAT Registration No. 345 7171 50

Email Disclaimer:
The information contained  in this email including attachments are confidential and intended for the sole use of the individual or company to whom it is addressed. If you are not the  intended recipient, the use of this information by disclosure, copying or  distribution is prohibited and may be unlawful.

We have taken precautions  to minimise the risk of transmitting software viruses, but we advise that you  carry out your own virus checks on any attachments to this message. We cannot  accept liability for any loss or damage caused by software viruses. If you  receive this email in error, or the transmission is incomplete or illegible,  please contact us on 020 8551 9999. Mulalley & Company Ltd routinely  monitors the content of emails sent and received via its network for the  purposes of ensuring compliance with its policies and  procedures.

Mulalley & Company Limited do not enter into or vary any  existing contract by email. For the avoidance of doubt, to be valid, all new  contracts and any variations to existing contracts must be clearly evidenced in  writing, and this intention to contract clearly attested by both  parties.

**Comment by jakobehn** [comment]
The link to LigGit2 was just for informational purpose :-)

It should work after yo have installed Git for Windows. Which install location did you specify when installing it?

**Comment by arame3333** [comment]
As I thought then.
I do not see a location to enter. See enclosed the first page of the setup wizard.
I executed the setup file from the Downloads folder.

Geoff (0777 5853 204)


Geoffrey Payne 
ICT Software Developer
Tel: 020 8551 9999
www.mulalley.co.uk
Consider the environment. Do you really need to print this email?
Registered Office: Teresa Gavin House, Woodford Avenue, Woodford Green, Essex IG8 8FA
Company No. 1534913
VAT Registration No. 345 7171 50

Email Disclaimer:
The information contained  in this email including attachments are confidential and intended for the sole use of the individual or company to whom it is addressed. If you are not the  intended recipient, the use of this information by disclosure, copying or  distribution is prohibited and may be unlawful.

We have taken precautions  to minimise the risk of transmitting software viruses, but we advise that you  carry out your own virus checks on any attachments to this message. We cannot  accept liability for any loss or damage caused by software viruses. If you  receive this email in error, or the transmission is incomplete or illegible,  please contact us on 020 8551 9999. Mulalley & Company Ltd routinely  monitors the content of emails sent and received via its network for the  purposes of ensuring compliance with its policies and  procedures.

Mulalley & Company Limited do not enter into or vary any  existing contract by email. For the avoidance of doubt, to be valid, all new  contracts and any variations to existing contracts must be clearly evidenced in  writing, and this intention to contract clearly attested by both  parties.

**Comment by jakobehn** [comment]
The screenshot didn't come through. Usually, GfW is installed at C:\Program Files\Git or C:\Program Files (x86)\Git.  

The extension looks in multiple places to track down the installation path, and should find it should it would be interesting to know where Git is installed on your machine

**Comment by arame3333** [comment]
Hi Jakob,
Thank you for your reply.
On my machine Git is stored on C:\Program Files\Git.
I have added you on my safe senders list and hopefully you can get the enclosed screenshot.

Geoff



Geoffrey Payne 
ICT Software Developer
Tel: 020 8551 9999
www.mulalley.co.uk
Consider the environment. Do you really need to print this email?
Registered Office: Teresa Gavin House, Woodford Avenue, Woodford Green, Essex IG8 8FA
Company No. 1534913
VAT Registration No. 345 7171 50

Email Disclaimer:
The information contained  in this email including attachments are confidential and intended for the sole use of the individual or company to whom it is addressed. If you are not the  intended recipient, the use of this information by disclosure, copying or  distribution is prohibited and may be unlawful.

We have taken precautions  to minimise the risk of transmitting software viruses, but we advise that you  carry out your own virus checks on any attachments to this message. We cannot  accept liability for any loss or damage caused by software viruses. If you  receive this email in error, or the transmission is incomplete or illegible,  please contact us on 020 8551 9999. Mulalley & Company Ltd routinely  monitors the content of emails sent and received via its network for the  purposes of ensuring compliance with its policies and  procedures.

Mulalley & Company Limited do not enter into or vary any  existing contract by email. For the avoidance of doubt, to be valid, all new  contracts and any variations to existing contracts must be clearly evidenced in  writing, and this intention to contract clearly attested by both  parties.

**Comment by arame3333** [comment]
I uninstalled and reinstalled Git and now it is working.


Geoffrey Payne 
ICT Software Developer
Tel: 020 8551 9999
www.mulalley.co.uk
Consider the environment. Do you really need to print this email?
Registered Office: Teresa Gavin House, Woodford Avenue, Woodford Green, Essex IG8 8FA
Company No. 1534913
VAT Registration No. 345 7171 50

Email Disclaimer:
The information contained  in this email including attachments are confidential and intended for the sole use of the individual or company to whom it is addressed. If you are not the  intended recipient, the use of this information by disclosure, copying or  distribution is prohibited and may be unlawful.

We have taken precautions  to minimise the risk of transmitting software viruses, but we advise that you  carry out your own virus checks on any attachments to this message. We cannot  accept liability for any loss or damage caused by software viruses. If you  receive this email in error, or the transmission is incomplete or illegible,  please contact us on 020 8551 9999. Mulalley & Company Ltd routinely  monitors the content of emails sent and received via its network for the  purposes of ensuring compliance with its policies and  procedures.

Mulalley & Company Limited do not enter into or vary any  existing contract by email. For the avoidance of doubt, to be valid, all new  contracts and any variations to existing contracts must be clearly evidenced in  writing, and this intention to contract clearly attested by both  parties.

**Comment by jakobehn** [comment]
Ok, thanks for following up on this. Not sure what went wrong the first time you installed it, but I'm glad that it works now
