### ISSUE TITLE
Performance issues for all operations

### ISSUE THREAD

**Issue by fabiostawinski** [jakobehn/GitFlow.VS#61]
I am experimenting some bad performance when using git flow extension, is there some tips what we could do to improve the git flow performance? git operations are very quick, and take seconds, for git flow it sometimes takes minutes.

**Comment by jakobehn** [comment]
The extension is behind the scene using the git flow scripts. Do you experience the same performance if you run the git flow commands from command line? E.g. git flow feature start MYFEATURE

**Comment by fabiostawinski** [comment]
I tried in VS and command-line, and seems that the results are similar, it is taking now 21 seconds to create the feature branch. 

git flow feature checkout "MYFEATURE" -> took 14 seconds. 

git checkout -b MYFEATURE -> Take less than 1 second.

Is that normal? I think there is something in my environment that can be improved... just now have no clue yet what to do.

**Comment by jakobehn** [comment]
Not sure.  I suggest that you post an issues over at the AVH fork of the gitflow scripts (which this extension uses):

https://github.com/petervanderdoes/gitflow-avh/

See also https://github.com/petervanderdoes/gitflow-avh/issues/52 for some tips

**Comment by fabiostawinski** [comment]
Great, thanks... I will post it there.
