### ISSUE TITLE
VS 2015 Can't switch between features

### ISSUE THREAD

**Issue by Samvrie** [jakobehn/GitFlow.VS#7]
Hi, it seems that i can't switch between **features** on my projet with *GitFlow*, i have to go to the **Branch** and then switch feature. GitFlow actually see that i switched features.

Hope it can help.

**Comment by jakobehn** [comment]
In the features list, you should be able to right-click on the feature and select "Checkout" in order to switch branch. Does that not work?

![image](https://cloud.githubusercontent.com/assets/847244/6224782/213010ca-b682-11e4-9ae0-f07b7ca6ec91.png)

**Comment by Samvrie** [comment]
Yes it does work, i didn't expect the behaviors to be like this!
Thanks my bad!
