### ISSUE TITLE
Branch names containing spaces should be replaced with hyphens instead of underscores

### ISSUE THREAD

**Issue by fordprefect480** [jakobehn/GitFlow.VS#73]
Currently, the code in TrimBranchName() is replacing space characters in branch names with underscores. I suggest that it should use hyphens instead which appears to be the convention when naming branches (I could be wrong).

If folks aren't keen on that idea, perhaps this could be configurable via the Settings window?

**Comment by jakobehn** [comment]
Agree with this, will fix this in a PR. Not sure why I used underscore in the first place here! :-)

**Comment by jakobehn** [comment]
Released to marketplace, version 1.3.12.0
