### ISSUE TITLE
Creating a feature with an apostrophe in the name does not work

### ISSUE THREAD

**Issue by cveld** [jakobehn/GitFlow.VS#74]
When creating a feature with an apostrophe in the name nothing happens. The output panel simply states "creating feature".

On the commandline I get the following exception from git:
-> git flow feature start "cool-feature-about-id's"
D:/Program Files/Git/usr/bin/git-flow-feature: eval: line 146: unexpected EOF while looking for matching `''
D:/Program Files/Git/usr/bin/git-flow-feature: eval: line 147: syntax error: unexpected end of file

-> git --version
git version 2.13.1.windows.2

Expected behavior:
The same error on the console should be reported out within Visual Studio. Or, apostrophes should be blocked out from feature names.

**Comment by jakobehn** [comment]
Fixed, and released in 1.3.7.0

The issue with apostrophes is in the GitFlow AVH scripts that this extension uses. I simply added a check for apostrophes to avoid this behaviour
