### ISSUE TITLE
Bug: Finish Feature is using squash and no-ff even when option not selected

### ISSUE THREAD

**Issue by JamesEvolution** [jakobehn/GitFlow.VS#78]
Finish Feature is trying to squash commits, even when the option is not selected.

I've just updated Visual Studio Pro 2017 to 15.9.2 - when finishing a feature today there were new options: 
- Squash feature during merge
- Never fast-forward during the merge
![image](https://user-images.githubusercontent.com/33928277/49090874-8a86cf00-f256-11e8-91a7-e8655e632d71.png)

I don't want to squash my commits, so I left that option unchecked, and clicked the OK button.

The branch is changed to develop and a squash is staged, even though the option was not selected. Looking in the GitFlow.VS output window, the `squash` and `no-ff` flags are used even though the check boxes are not ticked:

```
Running git flow feature finish "feature-branch-name" --squash --no-ff
Your branch is up to date with 'origin/develop'.
```

**Comment by JamesEvolution** [comment]
I think the problem is line 145 and 146 in GitFlowActionsUI.xaml - I think the Binding for the checkboxes are wrong... They're missing `Feature...` from the binding.

```xaml
<CheckBox Grid.Row="4"  IsChecked="{Binding Squash}">Squash feature during merge</CheckBox>
<CheckBox Grid.Row="5"  IsChecked="{Binding NoFastForward}">Never fast-forward during the merge</CheckBox>
```

Should probably be

```xaml
<CheckBox Grid.Row="4"  IsChecked="{Binding FeatureSquash}">Squash feature during merge</CheckBox>
<CheckBox Grid.Row="5"  IsChecked="{Binding FeatureNoFastForward}">Never fast-forward during the merge</CheckBox>
```

**Comment by jakobehn** [comment]
Thanks definitely looks like a bug. Looking into it now

**Comment by DaneSpiritGOD** [comment]
i've got the same problem.
thanks for your fixure.

**Comment by jakobehn** [comment]
Just an update, I fixed the problems with the bindings yesterday, but when testing the feature it didn't actually work. For some reason, the extension doesn't detect properly when the finish operation is completed when using the squash feature.

I'm digging into it, but it might take a little longer than expected to get the fix out unfortunately

**Comment by JamesEvolution** [comment]
@jakobehn thanks for looking into this.

I think the problem with squash could be because when you squash you have to commit the squashed commit again. I discovered this by opening another git client (tower) after trying to finish a feature. It said I had staged changes and needed to commit my squash.

**Comment by jakobehn** [comment]
Yes, the git flow scripts launches the defaul editor and then waits for it to be closed. I'm trying to show this information within the extension

Side question: Should these options (squash and never fast forward) be default true of false?

**Comment by JamesEvolution** [comment]
Personally I feel they should default to false - they should mirror the defaults for gitflow. 
If you have to specify a flag in the command line, then it's not a default option.

**Comment by jakobehn** [comment]
Agreed! 

So, the best thing I can do right now is to show a message to the user that they need to close the editor windows that is triggered by the git commit that gitflow does:

![image](https://user-images.githubusercontent.com/847244/49153103-12cba980-f315-11e8-8076-5397f7fe5e47.png)

I also extended the default timeout when doing a squash to avoid timeouts

**Comment by jakobehn** [comment]
Released to marketplace, version 1.3.12.0

**Comment by JamesEvolution** [comment]
Looks good - thanks for fixing

**Comment by mohdemraan** [comment]
Thanks for the quick fix. We also noticed this issue today. After latest version it is working fine.

**Comment by DaneSpiritGOD** [comment]
thanks so much.
