### ISSUE TITLE
GitFlowActionSection crashes on creation

### ISSUE THREAD

**Issue by wooboo** [jakobehn/GitFlow.VS#8]
While opening GitFlow page in TeamExplorer on existing repository I get this error:
```
System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Object reference not set to an instance of an object.

Resulting in: An exception occurred while trying to create an instance of type 'GitFlowVS.Extension.GitFlowActionSection'.

Resulting in: Cannot activate part 'GitFlowVS.Extension.GitFlowActionSection'.
Element: GitFlowVS.Extension.GitFlowActionSection -->  GitFlowVS.Extension.GitFlowActionSection

Resulting in: Cannot get export 'GitFlowVS.Extension.GitFlowActionSection (ContractName="Microsoft.TeamFoundation.Controls.ITeamExplorerSection")' from part 'GitFlowVS.Extension.GitFlowActionSection'.
Element: GitFlowVS.Extension.GitFlowActionSection (ContractName="Microsoft.TeamFoundation.Controls.ITeamExplorerSection") -->  GitFlowVS.Extension.GitFlowActionSection

   at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass7`2.<CreateStronglyTypedExportFactoryOfTM>b__6()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()
```

**Comment by jakobehn** [comment]
Thanks. Is this VS2013 or VS2015? And if you could include the exact version number that would be great

**Comment by wooboo** [comment]
It's VS Ultimate 2013 v12.0.31101.00 Update 4
GitFlow.VS.Extension 1.0
I've messed up a little with branches but I think I have it ok now (or not).
I've created a clean repo and it works fine, but I want to use it in my project.

**Comment by jakobehn** [comment]
Hmm OK. Would it be possible to share the repo with me, to see if I can reproduce the problem?

**Comment by wooboo** [comment]
No, I'm not able to share the project but I've fixed it I think.
While initializing the repo with GitFlow something went wrong and created only one gitflow entry in .git\config file.
I've cleaned up the config and was able to initialize it again, and it works now.

**Comment by jakobehn** [comment]
OK, thanks for the info! I have noticed something similar, if the git settings (username, email) is not properly configured then the init command fails, and the extension becomes unhappy. 

I'll fix this to make sure that the extension handles this properly.

**Comment by chandramouleswaran** [comment]
I ran into this issue - I did not have the develop branch in my repo while trying the plugin.

I removed the following from the .git\config file after creating the branch. GitFlow went back to the "Initialize" screen.

[gitflow "branch"]
	master = master

**Comment by jasperdelange** [comment]
I think I've narrowed it down...

`git flow init` fails to complete if there is another branch besides master but no develop branch. Adding these lines to .git/config
>[gitflow "branch"]
>master = master

I've created a shell script do help demonstrate the issue:
https://gist.github.com/jasperdelange/3983975463b04fa77678

If you then add the repository to Visual Studio and go to GitFlow you can see the exception (both VS2013.4 and VS2015 Preview; although VS2015 throws a TargetInvocationException).

If you create a develop branch and then run `git flow init -f` the init is completed and the extension works fine.

**Comment by jakobehn** [comment]
Thanks Jasper, I did actually narrow this down to last night. And as you say, if you have another branch next to master git flow will fail if you try to specify another name for develop branch.

However, it will succeed if you specify that branch name as the develop branch. But if you want another branch to be your develop branch you must create that manually first and then rerun initialize.

As mentioned above, I need to fix the extension so that it handles a partially failed init operation

**Comment by jakobehn** [comment]
Added a more complete initialized check so that a partially failed init doesn't cause the extension to crasch. Instead, it will let you run initialize again
