### ISSUE TITLE
support vs 2019

### ISSUE THREAD

**Issue by abuassar** [jakobehn/GitFlow.VS#84]
visual studio 2019 is around the corner, please kindly add support for it.

**Comment by jakobehn** [comment]
It has been available for VS2019 since december:
https://marketplace.visualstudio.com/items?itemName=vs-publisher-57624.GitFlowforVisualStudio2019

**Comment by abuassar** [comment]
awosome, thanks for your hard work

**Comment by josesalgueiro** [comment]
Please can you publish the source code for 2019. I know it must work asynchronously and I couldn't put it to work.
Thanks

**Comment by jakobehn** [comment]
The code for VS2019 has now been merged to master

**Comment by josesalgueiro** [comment]
@jakobehn, thanks for your fast response.
Now when I install the extension the Git Flow tab option does not show in the Team Explorer window.
What I am missing?
Tanks
