### ISSUE TITLE
No error notification if there's a failure when creating a release

### ISSUE THREAD

**Issue by yannduran** [jakobehn/GitFlow.VS#86]
Visual Studio: 2019
GitFlow: 1.3.12

The last few days when I create a _release_, I've forgotten that I have unstaged changes. But thinking that I've created a successful _release_, I go ahead and make final commits for docs and version number not realising there's been a problem.

When I go back to finish the _release_, there's no _release_ listed. There was no notification of any failure, until I go and look in the output window for GitFlow.

In there I find the following error:

> Running git flow release start "vX.Y.Z"
> **Fatal**: Working tree contains unstaged changes. **Aborting**.

Like most other errors seem to be, this error should be reported in the Team Explorer's notification bar.

**Comment by andrewyakonyuk** [comment]
Hi @jakobehn ,

I created the pull request #95  that fixes the reported issue. 
Please take a look.
Thanks.

**Comment by jakobehn** [comment]
Thanks Andrew!

I have merged the PR and published a new version of the extension (1.4.2.0)

**Comment by yannduran** [comment]
Thanks @andrewyakonyuk!
