### ISSUE TITLE
Support for Visual Studio 2019

### ISSUE THREAD

**Issue by WSt89** [jakobehn/GitFlow.VS#88]
Hello, is there a new version for Visual Studio 2019 planned?

**Comment by jakobehn** [comment]
It already exists: https://marketplace.visualstudio.com/items?itemName=vs-publisher-57624.GitFlowforVisualStudio2019

**Comment by WSt89** [comment]
Oh I see, I somehow missed it in my visual studio search results when searching for "git flow". It's installed now. Thank you very much.
