### ISSUE TITLE
Git Flow seemingly never stops if user has no command line git credentials store

### ISSUE THREAD

**Issue by jbattermann** [jakobehn/GitFlow.VS#9]
Jakob,

I completed my first feature started via your Git Flow extension and wanted to go ahead and finish it, but the progress bar just kept going and going, and nothing was apparently happening.

Looking at the running processes, there were 3 git*.exe ones running but basically idle and after closing VS, killing the git processes and calling git flow finish myfeature from commandline, git was pretty quickly asking for credentials.. and after entering them etc it did finish in just a few seconds.

Now I tried the same with another feature in VS and the 'GitFlow.VS' output does not show the credentials-entering request and thereby gives no indication to what's going on and why it is 'taking forever'.

Now while having credentials stored in e.g. [git-credential-winstore](https://gitcredentialstore.codeplex.com/) or the one the [GitHub Windows client](https://help.github.com/articles/caching-your-github-password-in-git/) brings along does solve this problem, it would help if the VS output pane would, if credentials are required, either allow me to enter them there or at least give some sort of indication that those are missing.

Cheers!
-J

**Comment by jakobehn** [comment]
Thanks Jörg, I'll look into this.

**Comment by pcolmer** [comment]
Unfortunately, the credentials workaround doesn't seem to work if Visual Studio Online is used, perhaps because of the way VSO implements authentication :-(

**Comment by jbattermann** [comment]
@pcolmer by default VSO uses (afaik) an OAuth based authentication approach, you can however create and use plain username/password combination, too see e.g. http://www.visualstudio.com/en-us/integrate/get-started/auth/overview how to set them up.

**Comment by pcolmer** [comment]
@jbattermann Thanks for the tip - that fixed it. I've configured git to use the Windows Credentials store, and Windows appears to have remembered my username and password for the VSO URL but it is still prompting me. Not sure why but if I stick to finishing features at the command line, I guess it isn't too big a deal for now.

**Comment by jakobehn** [comment]
I'll see if I can add code to the extension that checks if you are being prompted for credentials, to avoid the blocking issues. But I won't be able to authenticate of course

**Comment by pcolmer** [comment]
@jakobehn Looking at (or perhaps even reading for the first time!) https://msdn.microsoft.com/en-us/library/dd286572.aspx#setup, their recommendation, like @jbattermann, is to use http://gitcredentialstore.codeplex.com/. Although the documentation at https://help.github.com/articles/caching-your-github-password-in-git/ says that msysgit can be configured to store credentials by using "git config --global credential.helper wincred", I couldn't stop it prompting for credentials. gitcredentialstore, on the other hand, not only prompts with a GUI interface (which may solve the blocking problem) but also properly caches the credentials and re-uses them in the future.

It may, therefore, be sufficient to add some more documentation to guide the user through some additional setup steps.

**Comment by jakobehn** [comment]
I just published a new version (0.9.22) that added works around this problem by using a timeout when running git flow. If the timeout hits, a notification message is shown to the user with a suggestion what might be the problem. Unfortunately since git.exe does not output the credentials prompt to stdout, it is quite hard to capture this output properly. If anyone has some info on how to capture the screen buffer please contact me

**Comment by yannduran** [comment]
@jakobehn 

Does this code give you any clues? Although I notice it's currently using StandardOutput, maybe you could modify the code in some way to achieve what you need to do?

On the other hand, it might be exactly what you've already tried, but I thought I'd put it out there, just in case it helped.

    protected static string GetProcessOutput(string name, string args)
    {
        try
        {
            //var path = Environment.GetFolderPath(Environment.SpecialFolder.System);
            var p = new Process
            {
                StartInfo =
                {
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                    FileName = name,
                    Arguments=args,
                    WindowStyle = ProcessWindowStyle.Hidden
                }
            };
            p.Start();

            // NB: make sure to read to the end of the redirected stream before waiting
            var output = p.StandardOutput.ReadToEnd();

            p.WaitForExit();

            return output;
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
            return "";
        }
    }

**Comment by jakobehn** [comment]
Thanks Yann, the problem is that when Git prompts for credentials it does not stream it to StdOut, but instead writes directly to the console screen buffer (https://msdn.microsoft.com/en-us/library/windows/desktop/ms682088(v=vs.85).aspx). 

Reading from this is quite complicated, the API is pretty low level, so unfortunately I haven't been able to fix this yet.

**Comment by jbattermann** [comment]
[Jim Mischel wrote an MIT licensed library / sample code to access to screen buffers](http://stackoverflow.com/a/7488827/2591) .. which includes a console buffer reading sample, too. Not sure if you want to pull in external code here, but maybe it's worth a look.

**Comment by jakobehn** [comment]
Thank Jörg, I'll take a look at it! I actually think I found that broken link last time I checked around for implementing screen buffer support, but I didn't find the link to the sample :-)
