### ISSUE TITLE
Upgrade GitFlow scripts from AVH repo

### ISSUE THREAD

**Issue by jakobehn** [jakobehn/GitFlow.VS#90]
Latest release is 1.12.3
https://github.com/petervanderdoes/gitflow-avh/releases/tag/1.12.3

**Comment by yannduran** [comment]
Just curious Jakob, do you happen to know what the AVH acronym stands for?

**Comment by jakobehn** [comment]
No, curious myself :-)   Closing this one, since that release was merged in a long time ago
