### ISSUE TITLE
Consider implementing GVFS Protocol so extension will be compatible with VFS for Git

### ISSUE THREAD

**Issue by JonHeaton** [jakobehn/GitFlow.VS#92]
I recently created a large repository and I am using Microsoft's VFS for Git to solve some performance issues.  I would like to be able to use this extension but I get an exception about "Invalid data in index - incorrect header version" and I believe it to be related to VFS for Git storing the indexes differently and thus your extension is unable to verify the checksum on the index file. 

https://github.com/microsoft/VFSForGit/blob/master/Protocol.md

**Comment by jakobehn** [comment]
Its a great idea, however this extension depends on the GitFlow AVH scripts, that doesn't support this.
