### ISSUE TITLE
Visual Studio 16.8 has a new Git tool windows.  GitFlow should be moved out of Team Explorer window.

### ISSUE THREAD

**Issue by Phlow2001** [jakobehn/GitFlow.VS#97]
This project looks dead to me, but I'm going to report this issue anyway.  The new version of Visual Studio (16.8) has refactored the git experience.  As such, Team Explorer is now just for Azure DevOps.  The GitFlow tool is now out of place.

**Comment by InteXX** [comment]
@Phlow2001 

If by "out of place" you mean completely disappeared, I agree. At least on my machine, GitFlow is inaccessible with the new Git tooling.

Yours as well?

**Comment by jakobehn** [comment]
Unfortunately, the new Git tool window is not extensible (had an email conversation with the PM of the Git integration in Visual Studio, who told me this).

This extension will stay in the Team Explorer. Another option would be to create a separate, dedicated window of course
